// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqJPwYXCPowfrgTXxMja1AQY2ez4Vy3_0',
    appId: '1:49602864473:web:ff4b4a212eaacc5a22d848',
    messagingSenderId: '49602864473',
    projectId: 'solemne3-949af',
    authDomain: 'solemne3-949af.firebaseapp.com',
    databaseURL: 'https://solemne3-949af-default-rtdb.firebaseio.com',
    storageBucket: 'solemne3-949af.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlOwPUDumzbeDnyikZ_BK-bGc2K-Veby0',
    appId: '1:49602864473:android:528b80d37bb9f27c22d848',
    messagingSenderId: '49602864473',
    projectId: 'solemne3-949af',
    databaseURL: 'https://solemne3-949af-default-rtdb.firebaseio.com',
    storageBucket: 'solemne3-949af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKS76U5nTz5RaBbjfVMAP_U7SlDY7P7IU',
    appId: '1:49602864473:ios:3578bf4ed0e1a37022d848',
    messagingSenderId: '49602864473',
    projectId: 'solemne3-949af',
    databaseURL: 'https://solemne3-949af-default-rtdb.firebaseio.com',
    storageBucket: 'solemne3-949af.appspot.com',
    iosClientId: '49602864473-a60rh0m3bslrbsor6kb17ulvhcd7ushn.apps.googleusercontent.com',
    iosBundleId: 'com.example.lenguajes',
  );
}
